// config/tally_server_config.js
module.exports = {
    P:8831,
    Q:883,
    threshold:2,
    tally_servers_info:[
        {
            seq:1,
            port:10001
        },
        {
            seq:2,
            port:10002
        },
        {
            seq:3,
            port:10003
        },
        {
            seq:4,
            port:10004
        },
        {
            seq:5,
            port:10005
        }
    ],
    tally_server_path:'/Users/dick/Dropbox/Workspace/NODEJS_PROJECT/Evoting-Tally-Server/'
};